import type { Ucg } from './types'

/**
 * 示例 UCG：模拟一个迷你 FastAPI 项目的功能图。
 * 仅用于画布壳子展示，验证 UCG → 画布的渲染链路。
 */
export const sampleUcg: Ucg = {
  version: '0',
  manifest: {
    repo: 'demo/sample-app',
    commit: 'a1b2c3d',
    toolchain: { mock: '0.1.0' },
    generated_at: new Date().toISOString(),
  },
  nodes: [
    {
      id: 'route:POST /login',
      kind: 'route',
      name: 'POST /login',
      qualified_name: 'app.api.auth:login_route',
      language: 'python',
      location: { file: 'app/api/auth.py', start_line: 12, end_line: 28 },
      meta: { framework: 'fastapi' },
    },
    {
      id: 'fn:auth.login',
      kind: 'function',
      name: 'login',
      qualified_name: 'app.services.auth.login',
      language: 'python',
      location: { file: 'app/services/auth.py', start_line: 18, end_line: 56 },
    },
    {
      id: 'fn:auth.verify_password',
      kind: 'function',
      name: 'verify_password',
      qualified_name: 'app.services.auth.verify_password',
      language: 'python',
      location: { file: 'app/services/auth.py', start_line: 8, end_line: 16 },
    },
    {
      id: 'fn:token.issue',
      kind: 'function',
      name: 'issue_token',
      qualified_name: 'app.services.token.issue_token',
      language: 'python',
      location: { file: 'app/services/token.py', start_line: 22, end_line: 41 },
    },
    {
      id: 'data:User',
      kind: 'data_model',
      name: 'User',
      qualified_name: 'app.models.user.User',
      language: 'python',
      location: { file: 'app/models/user.py', start_line: 5, end_line: 38 },
    },
    {
      id: 'fn:user.get_by_email',
      kind: 'function',
      name: 'get_by_email',
      qualified_name: 'app.repos.user.get_by_email',
      language: 'python',
      location: { file: 'app/repos/user.py', start_line: 11, end_line: 19 },
    },
    {
      id: 'task:send_login_email',
      kind: 'task',
      name: 'send_login_email',
      qualified_name: 'app.tasks.email.send_login_email',
      language: 'python',
      location: { file: 'app/tasks/email.py', start_line: 7, end_line: 24 },
      meta: { framework: 'celery' },
    },
    {
      id: 'ext:bcrypt',
      kind: 'external',
      name: 'bcrypt',
      qualified_name: 'bcrypt',
      language: 'python',
      meta: { package: 'bcrypt' },
    },
    {
      id: 'ext:jwt',
      kind: 'external',
      name: 'PyJWT',
      qualified_name: 'jwt',
      language: 'python',
      meta: { package: 'pyjwt' },
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'route:POST /login',
      target: 'fn:auth.login',
      kind: 'route_to',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e2',
      source: 'fn:auth.login',
      target: 'fn:user.get_by_email',
      kind: 'call',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e3',
      source: 'fn:user.get_by_email',
      target: 'data:User',
      kind: 'read',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e4',
      source: 'fn:auth.login',
      target: 'fn:auth.verify_password',
      kind: 'call',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e5',
      source: 'fn:auth.verify_password',
      target: 'ext:bcrypt',
      kind: 'call',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e6',
      source: 'fn:auth.login',
      target: 'fn:token.issue',
      kind: 'call',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e7',
      source: 'fn:token.issue',
      target: 'ext:jwt',
      kind: 'call',
      confidence: 1,
      provenance: 'mock',
    },
    {
      id: 'e8',
      source: 'fn:auth.login',
      target: 'task:send_login_email',
      kind: 'publish',
      confidence: 0.7,
      provenance: 'mock',
      meta: { note: 'celery delay() 调用，标记为推断' },
    },
  ],
  unresolved: [
    {
      symbol: 'app.utils.audit.record',
      context: 'fn:auth.login',
      reason: '动态属性调用，静态分析无法解析',
    },
  ],
}
